### ISSUE TITLE
double-blind at SIGMOD and VLDB

### ISSUE THREAD

**Issue by emeryberger** [double-blind-reviewing/double-blind-reviewing.github.io#17]
Since 2001.
https://sigmodrecord.org/publications/sigmodRecord/0606/p29-inv-article-madden.pdf
"Starting with the 2001 SIGMOD conference, the
SIGMOD Chair, in consultation with the SIGMOD
Advisory Committee, imposed a double blind rule on
all future SIGMOD conferences."

**Comment by adam-morrison** [comment]
While SIGMOD is double blind, **VLDB is not**. From http://vldb.org/pvldb/vol15-submission/:

> VLDB is a single-blind conference. Therefore, authors MUST include their names and affiliations on the first page of the manuscript.

**Comment by emeryberger** [comment]
Thanks, will update!

**Comment by adam-morrison** [comment]
Great, thanks. Note that the "Historical notes" also needs updating, it still says "SIGMOD and VLDB have been double-blind..."
