### ISSUE TITLE
Crypto/Eurocrypt arxiv restrictions

### ISSUE THREAD

**Issue by rosulek** [double-blind-reviewing/double-blind-reviewing.github.io#9]
From https://eprint.iacr.org/about.html#publication:

> The view of IACR and the ePrint archive is that such a posting is permitted and that authors should not be penalized by conference program committees for having made such a posting.

Refers to eprint rather than arxiv, but the point is there. This is somewhat of an informal policy of the IACR covering Crypto/Eurocrypt, although I think in principle PC chairs have the authority to overrule it (which would be unpopular).

**Comment by emeryberger** [comment]
Thanks. Updated the `README.md` to reflect this.
